// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_p1Qirtm0Z",
    "aws_user_pools_web_client_id": "4d5mn0lrej8igks52feuksau6f",
    "oauth": {}
};

// cognito56288008_userpool_56288008-pawesome

export default awsmobile;
